// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Tracking;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tracking_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Tracking.entityManager;
    
    public static final List<String> Tracking.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Tracking.entityManager() {
        EntityManager em = new Tracking().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tracking.countTrackings() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tracking o", Long.class).getSingleResult();
    }
    
    public static List<Tracking> Tracking.findAllTrackings() {
        return entityManager().createQuery("SELECT o FROM Tracking o", Tracking.class).getResultList();
    }
    
    public static List<Tracking> Tracking.findAllTrackings(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tracking o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tracking.class).getResultList();
    }
    
    public static Tracking Tracking.findTracking(Long id) {
        if (id == null) return null;
        return entityManager().find(Tracking.class, id);
    }
    
    public static List<Tracking> Tracking.findTrackingEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tracking o", Tracking.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Tracking> Tracking.findTrackingEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tracking o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tracking.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Tracking.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tracking.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tracking attached = Tracking.findTracking(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tracking.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tracking.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tracking Tracking.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tracking merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
