// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Tracking;
import java.util.Date;

privileged aspect Tracking_Roo_JavaBean {
    
    public String Tracking.getId() {
        return this.id;
    }
    
    public void Tracking.setId(String id) {
        this.id = id;
    }
    
    public String Tracking.getName() {
        return this.name;
    }
    
    public void Tracking.setName(String name) {
        this.name = name;
    }
    
    public Date Tracking.getDeliveryTime() {
        return this.deliveryTime;
    }
    
    public void Tracking.setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }
    
    public Date Tracking.getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void Tracking.setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    
    public String Tracking.getStatus() {
        return this.status;
    }
    
    public void Tracking.setStatus(String status) {
        this.status = status;
    }
    
}
